plugins:
    - "jekyll-include-cache"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

exclude:
    - .idea/
    - dist/
    - node_modules/
    - .selcon/
include:
    - _pages
    - _docs

# Minimal mistakes config
minimal_mistakes_skin: "dark"
title: Selcon Documentation
description: >
    Self-contained markup compiler.
locale: en-GB
url: https://docs.tecc.me/selcon
repository: tecc/selcon
breadcrumbs: true
read_time: true
atom_feed:
    hide: true
defaults:
    # _pages
    -   scope:
            path: ""
            type: pages
        values:
            layout: single
            author_profile: false
    # _docs
    -   scope:
            path: ""
            type: docs
        values:
            layout: single
            sidebar:
                nav: "docs"

encoding: "utf-8"

collections:
    pages:
        output: true
        permalink: /:path/
    docs:
        output: true
        permalink: /guide/:path/