#
# SPDX-FileCopyrightText: 2021 Cae Lundin <tecc@tecc.me>
#
# SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-KDE-Accepted-LGPL
#
indent_style: space
indent_size: 4
end_of_line: lf
insert_final_newline: true
